version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: trademe_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - trademe_network


  # 后端服务
  user-service:
    build: 
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: trademe_user_service
    environment:
      NODE_ENV: development
      # 统一使用SQLite（Prisma连接串）
      DATABASE_URL: file:/app/data/trademe.db
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - redis
    volumes:
      - ./backend/user-service:/app
      - /app/node_modules
    networks:
      - trademe_network

  trading-service:
    build:
      context: ./backend/trading-service
      dockerfile: Dockerfile
    container_name: trademe_trading_service
    environment:
      # 统一使用SQLite（SQLAlchemy+aiosqlite连接串）
      DATABASE_URL: sqlite+aiosqlite:///app/data/trademe.db
      REDIS_URL: redis://redis:6379
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - ./backend/trading-service:/app
    networks:
      - trademe_network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trademe_frontend
    environment:
      VITE_API_BASE_URL: http://localhost:3001/api/v1
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - trademe_network

volumes:
  redis_data:

networks:
  trademe_network:
    driver: bridge
