import { create } from 'zustand'
import { persist } from 'zustand/middleware'

// 翻译文本
const translations = {
  zh: {
    // 登录页面
    welcomeTitle: '欢迎来到Trademe',
    welcomeSubtitle: '专业的数字货币策略交易平台',
    activeUsers: '活跃用户',
    tradingVolume: '交易量',
    uptime: '系统稳定性',
    platformDescription: '基于人工智能的量化交易平台，支持多交易所、自动化策略和智能风控',
    createAccount: '创建账户',
    accountLogin: '账户登录',
    registerSubtitle: '开始您的智能交易之旅',
    loginSubtitle: '欢迎回来，请登录您的账户',
    orContinueWith: '或者使用其他方式',
    username: '用户名',
    enterUsername: '请输入用户名',
    email: '邮箱地址',
    enterEmail: '请输入邮箱地址',
    password: '密码',
    enterPassword: '请输入密码',
    confirmPassword: '确认密码',
    enterPasswordAgain: '请再次输入密码',
    forgotPassword: '忘记密码',
    enterEmailForReset: '输入邮箱以重置密码',
    sendReset: '发送重置链接',
    processing: '处理中...',
    login: '登录',
    haveAccount: '已有账户？',
    noAccount: '还没有账户？',
    loginNow: '立即登录',
    registerNow: '立即注册',
    byRegisteringAgree: '注册即表示您同意我们的',
    termsOfService: '服务条款',
    and: '和',
    privacyPolicy: '隐私政策',
    
    // 错误消息
    userNotFound: '用户不存在，请检查邮箱地址',
    wrongPassword: '密码错误，请重试或重置密码',
    loginFailed: '登录失败，请重试',
    loginSuccess: '登录成功',
    registerSuccess: '注册成功',
    authError: '认证错误，请重试',
    googleLoginSuccess: 'Google登录成功',
    googleLoginFailed: 'Google登录失败',
    googleLoginError: 'Google登录出错',
    passwordResetSent: '密码重置链接已发送到您的邮箱',
    passwordResetFailed: '发送重置链接失败',
    passwordResetError: '重置密码时出错',
    wantToRegister: '该用户不存在，是否要注册新账户？',
    
    // 其他页面通用
    dashboard: '仪表板',
    strategies: '策略管理',
    trading: '实盘交易',
    backtest: '回测分析',
    aiAssistant: 'AI助手',
    market: '市场数据',
    portfolio: '投资组合',
    settings: '设置',
    logout: '退出登录',
    profile: '个人资料',
    notifications: '通知',
    help: '帮助中心',
    about: '关于我们',
    contact: '联系我们',
    language_setting: '语言',
    theme_setting: '主题',
    lightMode: '浅色模式',
    darkMode: '深色模式',
    
    // 页面特定翻译
    chartTrading: '图表交易',
    liveTrading: '实盘交易',
    tradingNotes: '交易心得',
    apiManagement: 'API管理',
    accountCenter: '账户中心',
    membershipManagement: '会员管理',
    personalSettings: '个人设置',
    
    // 概览页面
    tradingOverview: '交易概览',
    welcomeBack: '欢迎回来',
    checkTradingDataAndQuickActions: '查看您的交易数据和快速操作',
    realTimeConnected: '实时连接',
    connectionLost: '连接断开',
    totalStrategies: '策略总数',
    running: '运行中',
    totalProfit: '总收益',
    winRate: '胜率',
    quickActions: '快捷操作',
    strategiesManagement: '策略管理',
    viewAndManageStrategies: '查看和管理您的交易策略',
    startAutomatedTrading: '开始实盘自动化交易',
    strategyBacktest: '策略回测',
    testStrategyPerformance: '测试策略历史表现',
    aiAssistant: 'AI助手',
    getIntelligentTradingAdvice: '获取智能交易建议',
    recentStrategies: '最近策略',
    viewAll: '查看全部',
    loadingStrategies: '加载策略中...',
    viewDetails: '查看详情',
    noStrategies: '暂无策略',
    createFirstStrategy: '开始创建您的第一个交易策略',
    createStrategy: '创建策略',
    upgradeToCreate: '升级后创建',
    createStrategyRequiresPremium: '创建策略需要升级到高级版本',
    stopped: '已停止',
    tradingPair: '交易对',
    timeframe: '周期',
    
    // 策略页面
    liveTrading: '实盘交易',
    monitorRunningStrategies: '监控运行中的实盘交易，查看收益和交易详情',
    totalLiveStrategies: '总实盘数',
    runningLive: '运行中',
    stoppedLive: '已停止',
    pausedLive: '已暂停',
    searchStrategies: '搜索策略...',
    allStatus: '全部',
    paused: '已暂停',
    strategyName: '策略名称',
    status: '状态',
    profitLoss: '盈亏',
    lastUpdate: '最近更新',
    actions: '操作',
    start: '启动',
    stop: '停止',
    pause: '暂停',
    delete: '删除',
    viewDetails: '查看详情',
    confirmDelete: '确定要删除策略',
    strategyDeleted: '策略已删除',
    strategyStarted: '已启动',
    strategyStopped: '已停止',
    strategyPaused: '已暂停',
    startStrategyRequiresPremium: '启动策略需要高级版本',
    loadingStrategiesError: '加载实盘失败',
    strategiesLoaded: '个实盘',
    noStrategiesMessage: '暂无策略数据',
    createFirstStrategyMessage: '创建您的第一个交易策略开始实盘交易',
    selected: '已选中',
    currentFilter: '当前筛选',
    clearFilter: '清除筛选',
    
    // AI聊天页面
    aiChatWelcome: '您好！我是Trademe AI交易助手。我可以帮您：\n\n• 📈 分析市场趋势和技术指标\n• 🤖 生成量化交易策略代码\n• 💡 提供交易建议和风险评估\n• 📊 解读回测结果和优化建议\n\n请告诉我您需要什么帮助？',
    aiChatRequiresPremium: 'AI对话功能需要升级到高级版本',
    aiResponseError: 'AI响应出错，请重试',
    sendMessage: '发送',
    typeMessage: '输入您的问题...',
    aiTyping: 'AI正在思考...',
    newChat: '新对话',
    
    // 回测页面
    strategyBacktest: '策略回测',
    verifyTradingStrategy: '验证您的交易策略，优化投资决策',
    totalBacktests: '总回测数',
    completedSuccessfully: '成功完成',
    executionFailed: '执行失败',
    createBacktest: '创建回测',
    backtestHistory: '回测历史',
    backtestConfig: '回测配置',
    selectStrategy: '选择策略',
    strategyRequired: '请选择策略',
    confirmDeleteBacktest: '确定要删除这个回测吗？',
    getStrategiesError: '获取策略列表失败',
    completed: '已完成',
    failed: '已失败',
    unknown: '未知',
    
    // 通用状态文本
    selectOption: '请选择...',
    required: '必填项',
    optional: '可选项',
    
    // 交易心得页面
    tradingNotes: '交易心得',
    shareTradeThoughts: '分享交易心得，学习交流经验',
    totalNotes: '心得总数',
    publicNotes: '公开心得',
    privateNotes: '私密心得',
    drafts: '草稿',
    myNotes: '我的心得',
    publicDiscussion: '公开讨论',
    createNote: '创建心得',
    writeTitle: '写下标题',
    shareTradeStory: '分享您的交易故事、心得体会',
    selectCategory: '选择分类',
    technicalAnalysis: '技术分析',
    fundamentalAnalysis: '基本面分析', 
    strategyDiscussion: '策略探讨',
    errorReview: '错误复盘',
    marketView: '市场观点',
    tradingPairOptional: '交易对（可选）',
    entryPrice: '入场价格',
    exitPrice: '出场价格',
    stopLoss: '止损价格',
    takeProfit: '止盈价格',
    positionSize: '仓位大小',
    tags: '标签',
    addTag: '添加标签',
    publicPost: '公开发布',
    saveDraft: '保存草稿',
    publishing: '发布中...',
    saving: '保存中...',
    searchNotes: '搜索心得...',
    allCategories: '全部分类',
    sortBy: '排序方式',
    newest: '最新',
    oldest: '最早',
    mostLiked: '最受欢迎',
    noNotesMessage: '还没有心得分享',
    createFirstNote: '写下您的第一篇交易心得',
    
    // API管理页面
    apiManagement: 'API管理',
    manageExchangeConnections: '管理交易所连接，配置API密钥',
    totalAPIs: 'API总数',
    activeAPIs: '活跃API',
    testConnection: '测试连接',
    addNewAPI: '添加新API',
    apiKeyManagement: 'API密钥管理',
    exchangeName: '交易所名称',
    apiKey: 'API密钥',
    secretKey: '密钥Secret',
    passphrase: '密码短语',
    permissions: '权限',
    connectionStatus: '连接状态',
    connected: '已连接',
    disconnected: '未连接',
    editAPI: '编辑API',
    deleteAPI: '删除API',
    confirmDeleteAPI: '确定要删除这个API配置吗？',
    
    // 账户中心页面  
    accountCenter: '账户中心',
    manageAccountAndSettings: '管理账户信息和系统设置',
    accountInfo: '账户信息',
    membershipInfo: '会员信息',
    securitySettings: '安全设置',
    systemSettings: '系统设置',
    basicInfo: '基本信息',
    avatar: '头像',
    changePassword: '修改密码',
    twoFactorAuth: '双重验证',
    currentPlan: '当前套餐',
    validUntil: '有效期至',
    upgrade: '升级',
    renewMembership: '续费会员',
    usageStatistics: '使用统计',
    changeAvatar: '更换头像',
    uploadImage: '上传图片',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmNewPassword: '确认新密码',
    saveChanges: '保存更改',
    cancel: '取消',
    
    // 会员计费相关
    basicUser: '初级用户',
    premiumUser: '高级用户',
    professionalUser: '专业用户',
    monthlyFee: '每月',
    apiKeyBinding: '个API密钥',
    dailyAIQuota: '每日AI助手额度',
    tickBacktestMonthly: '每月Tick级数据回测',
    tradingNotesStorage: '交易心得记录存储',
    indicatorsStrategies: '个指标/策略',
    liveInstances: '个实盘'
  },
  
  en: {
    // Login page
    welcomeTitle: 'Welcome to Trademe',
    welcomeSubtitle: 'Professional Cryptocurrency Strategy Trading Platform',
    activeUsers: 'Active Users',
    tradingVolume: 'Trading Volume',
    uptime: 'System Uptime',
    platformDescription: 'AI-powered quantitative trading platform with multi-exchange support, automated strategies, and intelligent risk control',
    createAccount: 'Create Account',
    accountLogin: 'Account Login',
    registerSubtitle: 'Start your intelligent trading journey',
    loginSubtitle: 'Welcome back, please login to your account',
    orContinueWith: 'Or continue with',
    username: 'Username',
    enterUsername: 'Enter username',
    email: 'Email Address',
    enterEmail: 'Enter email address',
    password: 'Password',
    enterPassword: 'Enter password',
    confirmPassword: 'Confirm Password',
    enterPasswordAgain: 'Enter password again',
    forgotPassword: 'Forgot Password',
    enterEmailForReset: 'Enter email to reset password',
    sendReset: 'Send Reset Link',
    processing: 'Processing...',
    login: 'Login',
    haveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    loginNow: 'Login Now',
    registerNow: 'Register Now',
    byRegisteringAgree: 'By registering, you agree to our ',
    termsOfService: 'Terms of Service',
    and: ' and ',
    privacyPolicy: 'Privacy Policy',
    
    // Error messages
    userNotFound: 'User not found, please check email address',
    wrongPassword: 'Wrong password, please try again or reset password',
    loginFailed: 'Login failed, please try again',
    loginSuccess: 'Login successful',
    registerSuccess: 'Registration successful',
    authError: 'Authentication error, please try again',
    googleLoginSuccess: 'Google login successful',
    googleLoginFailed: 'Google login failed',
    googleLoginError: 'Google login error',
    passwordResetSent: 'Password reset link has been sent to your email',
    passwordResetFailed: 'Failed to send reset link',
    passwordResetError: 'Error resetting password',
    wantToRegister: 'User does not exist, would you like to register a new account?',
    
    // Common for other pages
    dashboard: 'Dashboard',
    strategies: 'Strategies',
    trading: 'Live Trading',
    backtest: 'Backtest',
    aiAssistant: 'AI Assistant',
    market: 'Market Data',
    portfolio: 'Portfolio',
    settings: 'Settings',
    logout: 'Logout',
    profile: 'Profile',
    notifications: 'Notifications',
    help: 'Help Center',
    about: 'About Us',
    contact: 'Contact Us',
    language_setting: 'Language',
    theme_setting: 'Theme',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    
    // 页面特定翻译
    chartTrading: 'Chart Trading',
    liveTrading: 'Live Trading',
    tradingNotes: 'Trading Notes',
    apiManagement: 'API Management',
    accountCenter: 'Account Center',
    membershipManagement: 'Membership Management',
    personalSettings: 'Personal Settings',
    
    // 概览页面
    tradingOverview: 'Trading Overview',
    welcomeBack: 'Welcome back',
    checkTradingDataAndQuickActions: 'View your trading data and quick actions',
    realTimeConnected: 'Real-time Connected',
    connectionLost: 'Connection Lost',
    totalStrategies: 'Total Strategies',
    running: 'Running',
    totalProfit: 'Total Profit',
    winRate: 'Win Rate',
    quickActions: 'Quick Actions',
    strategiesManagement: 'Strategies Management',
    viewAndManageStrategies: 'View and manage your trading strategies',
    startAutomatedTrading: 'Start automated live trading',
    strategyBacktest: 'Strategy Backtest',
    testStrategyPerformance: 'Test strategy historical performance',
    aiAssistant: 'AI Assistant',
    getIntelligentTradingAdvice: 'Get intelligent trading advice',
    recentStrategies: 'Recent Strategies',
    viewAll: 'View All',
    loadingStrategies: 'Loading strategies...',
    viewDetails: 'View Details',
    noStrategies: 'No Strategies',
    createFirstStrategy: 'Start creating your first trading strategy',
    createStrategy: 'Create Strategy',
    upgradeToCreate: 'Upgrade to Create',
    createStrategyRequiresPremium: 'Creating strategies requires premium upgrade',
    stopped: 'Stopped',
    tradingPair: 'Trading Pair',
    timeframe: 'Timeframe',
    
    // Strategy page
    liveTrading: 'Live Trading',
    monitorRunningStrategies: 'Monitor running live strategies, view profits and trading details',
    totalLiveStrategies: 'Total Live Strategies',
    runningLive: 'Running',
    stoppedLive: 'Stopped',
    pausedLive: 'Paused',
    searchStrategies: 'Search strategies...',
    allStatus: 'All',
    paused: 'Paused',
    strategyName: 'Strategy Name',
    status: 'Status',
    profitLoss: 'P&L',
    lastUpdate: 'Last Update',
    actions: 'Actions',
    start: 'Start',
    stop: 'Stop',
    pause: 'Pause',
    delete: 'Delete',
    viewDetails: 'View Details',
    confirmDelete: 'Are you sure you want to delete strategy',
    strategyDeleted: 'Strategy deleted',
    strategyStarted: 'started',
    strategyStopped: 'stopped',
    strategyPaused: 'paused',
    startStrategyRequiresPremium: 'Starting strategies requires premium version',
    loadingStrategiesError: 'Failed to load live strategies',
    strategiesLoaded: 'live strategies loaded',
    noStrategiesMessage: 'No strategy data available',
    createFirstStrategyMessage: 'Create your first trading strategy to start live trading',
    selected: 'Selected',
    currentFilter: 'Current filter',
    clearFilter: 'Clear filter',
    
    // AI Chat page
    aiChatWelcome: 'Hello! I am Trademe AI trading assistant. I can help you:\n\n• 📈 Analyze market trends and technical indicators\n• 🤖 Generate quantitative trading strategy code\n• 💡 Provide trading advice and risk assessment\n• 📊 Interpret backtest results and optimization suggestions\n\nWhat can I help you with?',
    aiChatRequiresPremium: 'AI chat feature requires premium version upgrade',
    aiResponseError: 'AI response error, please try again',
    sendMessage: 'Send',
    typeMessage: 'Type your question...',
    aiTyping: 'AI is thinking...',
    newChat: 'New Chat',
    
    // Backtest page
    strategyBacktest: 'Strategy Backtest',
    verifyTradingStrategy: 'Verify your trading strategies and optimize investment decisions',
    totalBacktests: 'Total Backtests',
    completedSuccessfully: 'Completed Successfully',
    executionFailed: 'Execution Failed',
    createBacktest: 'Create Backtest',
    backtestHistory: 'Backtest History',
    backtestConfig: 'Backtest Configuration',
    selectStrategy: 'Select Strategy',
    strategyRequired: 'Please select a strategy',
    confirmDeleteBacktest: 'Are you sure you want to delete this backtest?',
    getStrategiesError: 'Failed to get strategy list',
    completed: 'Completed',
    failed: 'Failed',
    unknown: 'Unknown',
    
    // Common status text
    selectOption: 'Please select...',
    required: 'Required',
    optional: 'Optional',
    
    // Trading Notes page
    tradingNotes: 'Trading Notes',
    shareTradeThoughts: 'Share trading insights and learn from experiences',
    totalNotes: 'Total Notes',
    publicNotes: 'Public Notes',
    privateNotes: 'Private Notes',
    drafts: 'Drafts',
    myNotes: 'My Notes',
    publicDiscussion: 'Public Discussion',
    createNote: 'Create Note',
    writeTitle: 'Write title',
    shareTradeStory: 'Share your trading story and insights',
    selectCategory: 'Select Category',
    technicalAnalysis: 'Technical Analysis',
    fundamentalAnalysis: 'Fundamental Analysis',
    strategyDiscussion: 'Strategy Discussion',
    errorReview: 'Error Review',
    marketView: 'Market View',
    tradingPairOptional: 'Trading Pair (Optional)',
    entryPrice: 'Entry Price',
    exitPrice: 'Exit Price',
    stopLoss: 'Stop Loss Price',
    takeProfit: 'Take Profit Price',
    positionSize: 'Position Size',
    tags: 'Tags',
    addTag: 'Add Tag',
    publicPost: 'Publish Publicly',
    saveDraft: 'Save Draft',
    publishing: 'Publishing...',
    saving: 'Saving...',
    searchNotes: 'Search notes...',
    allCategories: 'All Categories',
    sortBy: 'Sort By',
    newest: 'Newest',
    oldest: 'Oldest',
    mostLiked: 'Most Liked',
    noNotesMessage: 'No notes shared yet',
    createFirstNote: 'Write your first trading note',
    
    // API Management page
    apiManagement: 'API Management',
    manageExchangeConnections: 'Manage exchange connections and configure API keys',
    totalAPIs: 'Total APIs',
    activeAPIs: 'Active APIs',
    testConnection: 'Test Connection',
    addNewAPI: 'Add New API',
    apiKeyManagement: 'API Key Management',
    exchangeName: 'Exchange Name',
    apiKey: 'API Key',
    secretKey: 'Secret Key',
    passphrase: 'Passphrase',
    permissions: 'Permissions',
    connectionStatus: 'Connection Status',
    connected: 'Connected',
    disconnected: 'Disconnected',
    editAPI: 'Edit API',
    deleteAPI: 'Delete API',
    confirmDeleteAPI: 'Are you sure you want to delete this API configuration?',
    
    // Account Center page
    accountCenter: 'Account Center',
    manageAccountAndSettings: 'Manage account information and system settings',
    accountInfo: 'Account Information',
    membershipInfo: 'Membership Information',
    securitySettings: 'Security Settings',
    systemSettings: 'System Settings',
    basicInfo: 'Basic Information',
    avatar: 'Avatar',
    changePassword: 'Change Password',
    twoFactorAuth: 'Two-Factor Authentication',
    currentPlan: 'Current Plan',
    validUntil: 'Valid Until',
    upgrade: 'Upgrade',
    renewMembership: 'Renew Membership',
    usageStatistics: 'Usage Statistics',
    changeAvatar: 'Change Avatar',
    uploadImage: 'Upload Image',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    
    // Membership billing related
    basicUser: 'Basic User',
    premiumUser: 'Premium User',
    professionalUser: 'Professional User',
    monthlyFee: 'per month',
    apiKeyBinding: 'API keys',
    dailyAIQuota: 'daily AI assistant quota',
    tickBacktestMonthly: 'monthly tick-level backtests',
    tradingNotesStorage: 'trading notes storage',
    indicatorsStrategies: 'indicators/strategies',
    liveInstances: 'live instances'
  }
}

interface LanguageState {
  language: 'zh' | 'en'
  setLanguage: (lang: 'zh' | 'en') => void
  t: (key: string) => string
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'zh',
      
      setLanguage: (lang) => set({ language: lang }),
      
      t: (key: string) => {
        const lang = get().language
        return (translations[lang] as any)[key] || key
      }
    }),
    {
      name: 'language-storage',
      getStorage: () => localStorage
    }
  )
)